server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/recreateu
    username: root
    password: jhj!236884400
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
# Hibernate 로깅 활성화
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE